"use client";

import React, { useState } from "react";
import { ArrowLeft, Save, FileText, AlertCircle, Edit3, Plus, Trash2, ChevronRight, Download } from "lucide-react";
import { Button } from "@/components/ui/Button";
import Link from "next/link";
import { cn } from "@/lib/utils";
import { useRouter } from "next/navigation";

export default function QuoteBuilderPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = React.use(params);
  const router = useRouter();
  
  return (
    <div className="max-w-7xl mx-auto pb-20">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
        <div>
          <Link href={`/sub-user/projects/${id}/results`} className="inline-flex items-center gap-1 text-sm font-bold text-gray-500 hover:text-gray-900 dark:hover:text-white mb-4 transition-colors">
            <ArrowLeft className="w-4 h-4" /> Back to AI Results
          </Link>
          <h1 className="text-[28px] font-bold text-gray-900 dark:text-white leading-tight">Quote Builder</h1>
          <p className="text-sm text-gray-500 dark:text-gray-400 font-medium">Residential Complex • united states</p>
        </div>
        
        <div className="flex items-center gap-3">
          <Button variant="secondary" className="h-11 px-6 rounded-xl font-bold bg-white dark:bg-[#111827] border-gray-200 dark:border-gray-700 shadow-sm text-gray-700 dark:text-gray-200">
            <Save className="w-4 h-4 mr-2" /> Save Draft
          </Button>
          <Button 
            onClick={() => router.push(`/sub-user/projects/${id}/quote/preview`)}
            variant="primary" 
            className="h-11 px-6 rounded-xl font-bold bg-emerald-600 hover:bg-emerald-700 shadow-md shadow-emerald-200 dark:shadow-none"
          >
            <FileText className="w-4 h-4 mr-2" /> Preview Quote
          </Button>
        </div>
      </div>

      {/* Warning Banner */}
      <div className="bg-orange-50/80 dark:bg-orange-900/10 border border-orange-200 dark:border-orange-800/50 rounded-2xl p-4 flex gap-3 mb-8">
        <AlertCircle className="w-5 h-5 text-orange-500 flex-shrink-0 mt-0.5" />
        <div>
          <h4 className="text-[14px] font-bold text-orange-800 dark:text-orange-400 mb-0.5">Check AI Accuracy: Review your quote!</h4>
          <p className="text-[13px] text-orange-700/80 dark:text-orange-300">Please review all values and assumptions generated by the AI before exporting the final proposal.</p>
        </div>
      </div>

      <div className="flex flex-col lg:flex-row gap-8">
        
        {/* Main Content Form */}
        <div className="flex-1 space-y-8">
          
          {/* Client Details */}
          <section className="bg-white dark:bg-[#111827] border border-gray-100 dark:border-gray-800 rounded-3xl p-6 md:p-8 shadow-sm">
            <div className="flex justify-between items-center mb-6">
              <div>
                <h2 className="text-[18px] font-bold text-gray-900 dark:text-white mb-1">Client Details</h2>
                <p className="text-[13px] text-gray-500">To whom the quote is addressed</p>
              </div>
              <Button variant="secondary" className="h-8 px-4 rounded-lg font-bold bg-emerald-50 dark:bg-emerald-900/20 text-emerald-700 dark:text-emerald-400 border border-emerald-100 dark:border-emerald-800 text-[12px]">
                <Edit3 className="w-3.5 h-3.5 mr-2" /> Edit Details
              </Button>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-y-4 gap-x-8">
              <div>
                <div className="text-[12px] font-bold text-gray-400 mb-1">COMPANY NAME</div>
                <div className="text-[14px] font-semibold text-gray-900 dark:text-white">ABC Developers Inc.</div>
              </div>
              <div>
                <div className="text-[12px] font-bold text-gray-400 mb-1">CONTACT PERSON</div>
                <div className="text-[14px] font-semibold text-gray-900 dark:text-white">John Smith</div>
              </div>
              <div>
                <div className="text-[12px] font-bold text-gray-400 mb-1">EMAIL ADDRESS</div>
                <div className="text-[14px] font-semibold text-gray-900 dark:text-white">john@abcdevelopers.com</div>
              </div>
              <div>
                <div className="text-[12px] font-bold text-gray-400 mb-1">COMPANY ADDRESS</div>
                <div className="text-[14px] font-semibold text-gray-900 dark:text-white">123 Business Ave, Suite 100, New York, NY</div>
              </div>
            </div>
          </section>

          {/* Project & Quote Details */}
          <section className="bg-white dark:bg-[#111827] border border-gray-100 dark:border-gray-800 rounded-3xl p-6 md:p-8 shadow-sm">
            <h2 className="text-[18px] font-bold text-gray-900 dark:text-white mb-6">Project & Quote Details</h2>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block text-[13px] font-bold text-gray-700 dark:text-gray-300 mb-1.5">Project Name</label>
                <input type="text" defaultValue="Green Valley Residential Complex" className="w-full h-11 px-4 rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-900 text-[13px] font-medium focus:outline-none" />
              </div>
              <div>
                <label className="block text-[13px] font-bold text-gray-700 dark:text-gray-300 mb-1.5">Quote Number</label>
                <input type="text" defaultValue="Q-2026-042" className="w-full h-11 px-4 rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-900 text-[13px] font-medium focus:outline-none" />
              </div>
              <div>
                <label className="block text-[13px] font-bold text-gray-700 dark:text-gray-300 mb-1.5">Project Address</label>
                <input type="text" defaultValue="Dhaka, Bangladesh" className="w-full h-11 px-4 rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-900 text-[13px] font-medium focus:outline-none" />
              </div>
              <div>
                <label className="block text-[13px] font-bold text-gray-700 dark:text-gray-300 mb-1.5">Quote Date</label>
                <input type="text" defaultValue="May 20, 2026" className="w-full h-11 px-4 rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-900 text-[13px] font-medium focus:outline-none" />
              </div>
              <div>
                <label className="block text-[13px] font-bold text-gray-700 dark:text-gray-300 mb-1.5">Revision</label>
                <input type="text" defaultValue="02" className="w-full h-11 px-4 rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-900 text-[13px] font-medium focus:outline-none" />
              </div>
              <div>
                <label className="block text-[13px] font-bold text-gray-700 dark:text-gray-300 mb-1.5">Validity</label>
                <input type="text" defaultValue="30 Days from date of issue" className="w-full h-11 px-4 rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-900 text-[13px] font-medium focus:outline-none" />
              </div>
            </div>
          </section>

          {/* Pricing */}
          <section className="bg-white dark:bg-[#111827] border border-gray-100 dark:border-gray-800 rounded-3xl p-6 md:p-8 shadow-sm">
            <div className="flex justify-between items-center mb-6">
              <div>
                <h2 className="text-[18px] font-bold text-gray-900 dark:text-white mb-1">Pricing</h2>
                <p className="text-[13px] text-gray-500">Breakdown of costs</p>
              </div>
              <Button variant="secondary" className="h-8 px-4 rounded-lg font-bold bg-white border-gray-200 shadow-sm text-gray-700 text-[12px]">
                + Add Custom Row
              </Button>
            </div>
            
            <div className="border border-gray-200 dark:border-gray-800 rounded-xl overflow-hidden">
              <table className="w-full text-left text-[13px]">
                <thead className="bg-gray-50 dark:bg-gray-900 border-b border-gray-200 dark:border-gray-800">
                  <tr>
                    <th className="px-4 py-3 font-bold text-gray-500">Description</th>
                    <th className="px-4 py-3 font-bold text-gray-500 text-right w-32">Amount</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100 dark:divide-gray-800 font-medium">
                  <tr><td className="px-4 py-3">Div 01 - General Requirements</td><td className="px-4 py-3 text-right">$18,750</td></tr>
                  <tr><td className="px-4 py-3">Div 06 - Wood, Plastics & Composites</td><td className="px-4 py-3 text-right">$72,250</td></tr>
                  <tr><td className="px-4 py-3">Div 08 - Openings</td><td className="px-4 py-3 text-right">$148,500</td></tr>
                  <tr><td className="px-4 py-3">Div 09 - Finishes</td><td className="px-4 py-3 text-right">$245,500</td></tr>
                </tbody>
              </table>
            </div>
            
            <div className="mt-6 flex justify-end">
              <div className="w-64 space-y-3">
                <div className="flex justify-between text-[13px] font-bold text-gray-500">
                  <span>Subtotal</span>
                  <span className="text-gray-900 dark:text-white">$485,000</span>
                </div>
                <div className="flex justify-between items-center text-[13px] font-bold text-gray-500">
                  <span>Contingency %</span>
                  <input type="text" defaultValue="5%" className="w-16 h-8 px-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 text-right text-gray-900 dark:text-white focus:outline-none" />
                </div>
                <div className="flex justify-between text-[15px] font-black text-emerald-600 dark:text-emerald-400 pt-3 border-t border-gray-200 dark:border-gray-800">
                  <span>Total Amount</span>
                  <span>$509,250</span>
                </div>
              </div>
            </div>
          </section>

          {/* Scope of Work */}
          <section className="bg-white dark:bg-[#111827] border border-gray-100 dark:border-gray-800 rounded-3xl p-6 md:p-8 shadow-sm">
            <div className="flex justify-between items-center mb-6">
              <div>
                <h2 className="text-[18px] font-bold text-gray-900 dark:text-white mb-1">Scope of Work</h2>
                <p className="text-[13px] text-gray-500">Detailed breakdown by divisions</p>
              </div>
              <Button variant="secondary" className="h-8 px-4 rounded-lg font-bold bg-white border-gray-200 shadow-sm text-gray-700 text-[12px]">
                <Edit3 className="w-3.5 h-3.5 mr-2" /> Edit Text
              </Button>
            </div>
            
            <div className="space-y-6">
              <div>
                <h4 className="text-[14px] font-bold text-gray-900 dark:text-white mb-2">Division 06 - Wood, Plastics & Composites:</h4>
                <textarea className="w-full h-24 p-4 rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-900 text-[13px] text-gray-600 dark:text-gray-300 resize-none focus:outline-none" 
                  defaultValue="Supply and install a total of forty (40) solid core wooden doors complete with pre-hung frames, paint-grade factory finish, and all required accessories necessary for a complete and fully operational installation." />
              </div>
              <div>
                <h4 className="text-[14px] font-bold text-gray-900 dark:text-white mb-2">Division 08 - Openings:</h4>
                <textarea className="w-full h-24 p-4 rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-900 text-[13px] text-gray-600 dark:text-gray-300 resize-none focus:outline-none" 
                  defaultValue="Provide and install aluminum window framing systems with double-glazed insulated glass units covering approximately eighty-five (85) square meters in total area. All glazing systems shall include thermally broken aluminum frames." />
              </div>
            </div>
          </section>

          {/* Assumptions */}
          <section className="bg-white dark:bg-[#111827] border border-gray-100 dark:border-gray-800 rounded-3xl p-6 md:p-8 shadow-sm">
            <div className="flex justify-between items-center mb-4">
              <h2 className="text-[18px] font-bold text-gray-900 dark:text-white">Assumptions</h2>
              <Button variant="secondary" className="h-8 px-4 rounded-lg font-bold bg-white border-gray-200 shadow-sm text-gray-700 text-[12px]">
                <Edit3 className="w-3.5 h-3.5 mr-2" /> Edit
              </Button>
            </div>
            <ul className="list-disc list-inside text-[13px] text-gray-600 dark:text-gray-300 space-y-2 font-medium">
              <li>Site access provided as per tender specifications (6-11 AM for deliveries)</li>
              <li>Temporary facilities provided by general contractor</li>
              <li>Work area cleaned and protected by other trades before installation</li>
              <li>All substrates properly prepared and ready to receive finishes</li>
            </ul>
          </section>

          {/* Exclusions */}
          <section className="bg-white dark:bg-[#111827] border border-gray-100 dark:border-gray-800 rounded-3xl p-6 md:p-8 shadow-sm">
            <div className="flex justify-between items-center mb-4">
              <h2 className="text-[18px] font-bold text-gray-900 dark:text-white">Exclusions</h2>
              <Button variant="secondary" className="h-8 px-4 rounded-lg font-bold bg-white border-gray-200 shadow-sm text-gray-700 text-[12px]">
                <Edit3 className="w-3.5 h-3.5 mr-2" /> Edit
              </Button>
            </div>
            <ul className="list-disc list-inside text-[13px] text-gray-600 dark:text-gray-300 space-y-2 font-medium">
              <li>Electrical rough-in and fixture installation</li>
              <li>Plumbing rough-in and fixture installation</li>
              <li>HVAC ductwork and equipment installation</li>
              <li>Fire protection systems and equipment</li>
            </ul>
          </section>

          {/* Clarifications */}
          <section className="bg-white dark:bg-[#111827] border border-gray-100 dark:border-gray-800 rounded-3xl p-6 md:p-8 shadow-sm">
            <div className="flex justify-between items-center mb-4">
              <h2 className="text-[18px] font-bold text-gray-900 dark:text-white">Clarifications Needed</h2>
              <Button variant="secondary" className="h-8 px-4 rounded-lg font-bold bg-white border-gray-200 shadow-sm text-gray-700 text-[12px]">
                <Edit3 className="w-3.5 h-3.5 mr-2" /> Edit
              </Button>
            </div>
            <ul className="list-disc list-inside text-[13px] text-gray-600 dark:text-gray-300 space-y-2 font-medium">
              <li>Confirm exact working hours permitted for night work and any noise level restrictions</li>
              <li>Verify if temporary lighting and power are supplied by general contractor</li>
            </ul>
          </section>

          {/* Separate Prices */}
          <section className="bg-white dark:bg-[#111827] border border-gray-100 dark:border-gray-800 rounded-3xl p-6 md:p-8 shadow-sm">
            <div className="flex justify-between items-center mb-6">
              <h2 className="text-[18px] font-bold text-gray-900 dark:text-white">Separate Prices</h2>
              <Button variant="secondary" className="h-8 px-4 rounded-lg font-bold bg-white border-gray-200 shadow-sm text-gray-700 text-[12px]">
                + Add Price
              </Button>
            </div>
            
            <div className="border border-gray-200 dark:border-gray-800 rounded-xl p-5 mb-4">
              <div className="flex justify-between items-start mb-2">
                <div>
                  <span className="text-[10px] font-bold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded mr-2">SP-01</span>
                  <span className="text-[14px] font-bold text-gray-900 dark:text-white">Kitchen Appliances Package</span>
                </div>
                <div className="text-[15px] font-black text-gray-900 dark:text-white">$15,500</div>
              </div>
              <p className="text-[12px] text-gray-500 mb-4">Provide supply and installation of standard model appliances.</p>
              <div className="flex gap-2">
                <Button variant="secondary" className="h-7 px-3 rounded text-[11px] font-bold bg-gray-50 border-gray-200">Edit Details</Button>
                <Button variant="secondary" className="h-7 px-3 rounded text-[11px] font-bold bg-red-50 text-red-600 border-red-100">Delete</Button>
              </div>
            </div>
          </section>

          {/* Alternative Prices */}
          <section className="bg-white dark:bg-[#111827] border border-gray-100 dark:border-gray-800 rounded-3xl p-6 md:p-8 shadow-sm">
            <div className="flex justify-between items-center mb-6">
              <h2 className="text-[18px] font-bold text-gray-900 dark:text-white">Alternative Prices</h2>
              <Button variant="secondary" className="h-8 px-4 rounded-lg font-bold bg-white border-gray-200 shadow-sm text-gray-700 text-[12px]">
                + Add Alternative
              </Button>
            </div>
            
            <div className="border border-gray-200 dark:border-gray-800 rounded-xl p-5">
              <div className="flex justify-between items-start mb-2">
                <div>
                  <span className="text-[10px] font-bold text-blue-600 bg-blue-50 px-2 py-0.5 rounded mr-2">ALT-01</span>
                  <span className="text-[14px] font-bold text-gray-900 dark:text-white">Premium Appliances Package</span>
                </div>
                <div className="text-[15px] font-black text-gray-900 dark:text-white">$8,000</div>
              </div>
              <p className="text-[12px] text-gray-500 mb-4">Provide supply and installation of premium model appliances.</p>
              <div className="flex gap-2">
                <Button variant="secondary" className="h-7 px-3 rounded text-[11px] font-bold bg-gray-50 border-gray-200">Edit Details</Button>
                <Button variant="secondary" className="h-7 px-3 rounded text-[11px] font-bold bg-red-50 text-red-600 border-red-100">Delete</Button>
              </div>
            </div>
          </section>

        </div>

        {/* Sidebar / Floating Card for adding items */}
        <div className="w-full lg:w-[320px] flex-shrink-0">
          <div className="bg-white dark:bg-[#111827] border border-gray-100 dark:border-gray-800 rounded-3xl p-5 shadow-sm sticky top-28">
            <h3 className="text-[15px] font-bold text-gray-900 dark:text-white mb-4">Add Alternative Price</h3>
            
            <div className="space-y-4">
              <div>
                <label className="block text-[12px] font-bold text-gray-700 dark:text-gray-300 mb-1.5">Item Name</label>
                <input type="text" placeholder="e.g. Premium Tiles" className="w-full h-10 px-3 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-900 text-[13px] focus:outline-none" />
              </div>
              <div>
                <label className="block text-[12px] font-bold text-gray-700 dark:text-gray-300 mb-1.5">Amount ($)</label>
                <input type="text" placeholder="0.00" className="w-full h-10 px-3 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-900 text-[13px] focus:outline-none" />
              </div>
              <div>
                <label className="block text-[12px] font-bold text-gray-700 dark:text-gray-300 mb-1.5">Type</label>
                <select className="w-full h-10 px-3 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-900 text-[13px] focus:outline-none appearance-none">
                  <option>Alternative Price</option>
                  <option>Separate Price</option>
                </select>
              </div>
              <div>
                <label className="block text-[12px] font-bold text-gray-700 dark:text-gray-300 mb-1.5">Description</label>
                <textarea placeholder="Brief description..." className="w-full h-20 p-3 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-900 text-[13px] resize-none focus:outline-none" />
              </div>
              <Button variant="primary" className="w-full h-10 rounded-lg font-bold bg-emerald-600 hover:bg-emerald-700 shadow-sm text-white">
                Save Item
              </Button>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
